export enum LlmProviderName {
  Anthropic = 'anthropic',
  Azure = 'azure',
  Bedrock = 'bedrock',
  Cerebras = 'cerebras',
  Deepseek = 'deepseek',
  Gemini = 'gemini',
  Gpustack = 'gpustack',
  Groq = 'groq',
  Lmstudio = 'lmstudio',
  Minimax = 'minimax',
  Ollama = 'ollama',
  Openai = 'openai',
  OpenaiCompatible = 'openai-compatible',
  Openrouter = 'openrouter',
  Requesty = 'requesty',
  VertexAi = 'vertex-ai',
  ZaiPlan = 'zai-plan',
}
